controllers/FutsalController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Futsal;
use app\models\FutsalSearch;
use app\models\Pesertafutsal;
use app\models\PesertafutsalSearch;
use app\models\Model;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;

/**
 * FutsalController implements the CRUD actions for Futsal model.
 */
class FutsalController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Futsal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FutsalSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Futsal model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        
          //detail Sales
        $detailQuery = Pesertafutsal::find()
                ->where(['Kode_Futsal' => $id])
        ;
        $detailDataProvider = new ActiveDataProvider([
            'query' => $detailQuery,
        ]);
        
        return $this->render('view', [
            'model' => $this->findModel($id),
            'detailDataProvider'=>$detailDataProvider
        ]);
    }

    /**
     * Creates a new Futsal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
   /* public function actionCreate()
    {
        $model = new Futsal();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Kode_Futsal]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/
    
     public function actionCreate() {
        $model = new Futsal();
        $details = [ new Pesertafutsal];

        // proses isi post variable 
        if ($model->load(Yii::$app->request->post())) {
            $details = Model::createMultiple(Pesertafutsal::classname());
            Model::loadMultiple($details, Yii::$app->request->post());

            // assign default transaction_id
            foreach ($details as $detail) {
                $detail->Kode_Futsal = 0;
            }

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                                ActiveForm::validateMultiple($details), ActiveForm::validate($model)
                );
            }

            // validate all models
            $valid1 = $model->validate();
            $valid2 = Model::validateMultiple($details);
            $valid = $valid1 && $valid2;

            // jika valid, mulai proses penyimpanan
            if ($valid) {
                // mulai database transaction
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    // simpan master record                   
                    if ($flag = $model->save(false)) {
                        // simpan details record
                        foreach ($details as $detail) {
                            $detail->Kode_Futsal = $model->Kode_Futsal;
                            if (!($flag = $detail->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        // sukses, commit database transaction
                        // kemudian tampilkan hasilnya
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $model->Kode_Futsal]);
                    } else {
                        return $this->render('create', [
                                    'model' => $model,
                                    'details' => $details,
                        ]);
                    }
                } catch (Exception $e) {
                    // penyimpanan galga, rollback database transaction
                    $transaction->rollBack();
                    throw $e;
                }
            } else {
                return $this->render('create', [
                            'model' => $model,
                            'details' => $details,
                            'error' => 'valid1: ' . print_r($valid1, true) . ' - valid2: ' . print_r($valid2, true),
                ]);
            }
        } else {
            // inisialisai id 
            // diperlukan untuk form master-detail
            $model->Kode_Futsal = 0;
            // render view
            return $this->render('create', [
                        'model' => $model,
                        'details' => $details,
            ]);
        }
    }
    
     public function actionRegister() {
        $model = new Futsal();
        $details = [ new Pesertafutsal];

        // proses isi post variable 
        if ($model->load(Yii::$app->request->post())) {
            $details = Model::createMultiple(Pesertafutsal::classname());
            Model::loadMultiple($details, Yii::$app->request->post());

            // assign default transaction_id
            foreach ($details as $detail) {
                $detail->Kode_Futsal = 0;
            }

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                                ActiveForm::validateMultiple($details), ActiveForm::validate($model)
                );
            }

            // validate all models
            $valid1 = $model->validate();
            $valid2 = Model::validateMultiple($details);
            $valid = $valid1 && $valid2;

            // jika valid, mulai proses penyimpanan
            if ($valid) {
                // mulai database transaction
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    // simpan master record                   
                    if ($flag = $model->save(false)) {
                        // simpan details record
                        foreach ($details as $detail) {
                            $detail->Kode_Futsal = $model->Kode_Futsal;
                            if (!($flag = $detail->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        // sukses, commit database transaction
                        // kemudian tampilkan hasilnya
                        $transaction->commit();
                         $this->sendmail($model->Email_Perwakilan,$model->Nama_Team);
                          Yii::$app->session->setFlash('success', Yii::$app->params['pendaftaransukses']);
                        return $this->redirect(['/site/index']);
                    } else {
                        return $this->render('create', [
                                    'model' => $model,
                                    'details' => $details,
                        ]);
                    }
                } catch (Exception $e) {
                    // penyimpanan galga, rollback database transaction
                    $transaction->rollBack();
                    throw $e;
                }
            } else {
                
                var_dump($model->getErrors());
              //  var_dump($details->getErrors());
                return $this->render('create', [
                            'model' => $model,
                            'details' => $details,
                            'error' => 'valid1: ' . print_r($valid1, true) . ' - valid2: ' . print_r($valid2, true),
                ]);
            }
        } else {
            // inisialisai id 
            // diperlukan untuk form master-detail
            $model->Kode_Futsal = 0;
            // render view
            return $this->render('create', [
                        'model' => $model,
                        'details' => $details,
            ]);
        }
    }


    /**
     * Updates an existing Futsal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
  /*  public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Kode_Futsal]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }*/
    
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $details = $model->transactionDetails;
        if ($model->load(Yii::$app->request->post())) {
            $oldIDs = ArrayHelper::map($details, 'Kode_Peserta', 'Kode_Peserta');
            $details = Model::createMultiple(Pesertafutsal::classname(), $details);
            Model::loadMultiple($details, Yii::$app->request->post());
            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($details, 'Kode_Peserta', 'Kode_Peserta')));
            // assign default transaction_id
            foreach ($details as $detail) {

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ChangepasswordForm;
use app\models\User;

class SiteController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                // 'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
          return $this->render('index');
    }
    

    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    public function actionAbout() {
       // return $this->render('about');
         return $this->redirect(['index']);
    }
    
     public function actionChangepassword() {
        $model = new ChangepasswordForm;
        $modeluser = User::find()->where([
                    'username' => Yii::$app->user->identity->username
                ])->one();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                try {
                    $modeluser->password = $_POST['ChangepasswordForm']['newpass'];
                    if ($modeluser->save()) {
                        Yii::$app->getSession()->setFlash(
                                'success', 'Password sudah diubah'
                        );
                        return $this->redirect(['index']);
                    } else {
                        Yii::$app->getSession()->setFlash(
                                'error', 'Password tidak berubah'
                        );
                        return $this->redirect(['index']);
                    }
                } catch (Exception $e) {
                    Yii::$app->getSession()->setFlash(
                            'error', "{$e->getMessage()}"
                    );
                    return $this->render('changepassword', [
                                'model' => $model
                    ]);
                }
            } else {
                return $this->render('changepassword', [
                            'model' => $model
                ]);
            }
        } else {
            return $this->render('changepassword', [
                        'model' => $model
            ]);
        }
    }
    
    public function actionEventlainnya()
    {
         return $this->render('eventlainnya');
    }
    
    public function actionRute()
    {
         return $this->render('rute');
    }
    
    public function actionPendaftaranditutup()
    {
         return $this->render('pendaftaranditutup');
    }
    

    

}

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <link rel="shortcut icon" type="image/png" href="<?php echo Yii::getAlias('@web') ?>/images/indosaticon.png"/>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => Html::img('@web/images/indosaticon.png', ['alt' => Yii::$app->name]),
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top my-navbar',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'Home', 'url' => ['/site/index']],
                    ['label' => 'Digital Charity Run', 'url' => ['/charitywalk/register']],
                    ['label' => 'Fun Futsalista', 'url' => ['/futsal/register']],
                    ['label' => 'Gowes Bareng', 'url' => ['/citybike/registerawal']],
                    ['label' => 'Event Lainnya', 'url' => ['/site/eventlainnya']],
                    ['label' => 'Rute', 'url' => ['/site/rute'], 'visible' => !Yii::$app->user->isGuest],
                    ['label' => 'Voting', 'url' => ['/voting/index']],
                    ['label' => 'Administrator', 'url' => ['/transaksi/index'], 'items' => [

                            ['label' => 'Digital Charity Run', 'url' => ['/charitywalk/index']],
                            ['label' => 'Fun Futsalista', 'url' => ['/futsal/index']],
                            ['label' => 'Gowes Bareng', 'url' => ['/citybike/index']],
                            ['label' => 'Voting', 'url' => ['/voting/list']],
                            
                            ['label' => 'Pengguna', 'url' => ['/administrator/user']],
                            ['label' => 'Group Pengguna', 'url' => ['/administrator/role']],
                            ['label' => 'Aksi', 'url' => ['/administrator/route']],
                        ], 'visible' => !Yii::$app->user->isGuest],
                    Yii::$app->user->isGuest ? (
                            ['label' => 'Rute', 'url' => ['/site/rute']]
                            ) : (
                            '<li>'
                            . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                            . Html::submitButton(
                                    'Logout (' . Yii::$app->user->identity->username . ')', ['class' => 'btn btn-link']
                            )
                            . Html::endForm()
                            . '</li>'
                            )
                ],
            ]);
            NavBar::end();
            ?>

            <div class="container">
            <?=
            Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                'homeLink' => false, // add this line
            ])
            ?>
                <?= $content ?>
            </div>
                <br><br><br><br><br><br>
        </div>

        <footer class="footer">
             
             <div class="footer-bokeh"></div>
            <div class="container">
               
                
                <p class="pull-left">49 Tahun Indosat Ooredoo </p>






            </div>
        </footer>

<?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>