models/Citybike.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "citybike".
 *
 * @property integer $Kode_Citybike
 * @property string $Nama_Peserta
 * @property string $Email_Peserta
 * @property string $No_HP
 * @property string $NIK
 * @property string $Kategori_City_Bike
 * @property string $Ukuran_Jersey
 * @property string $Nama_Anggota_Keluarga
 * @property string $Keterangan
 */
class Citybike extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'citybike';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Nama_Peserta', 'Email_Peserta', 'No_HP', 'NIK', 'Kategori_City_Bike', 'Ukuran_Jersey','Jenis_Kelamin','Nama_Anggota_Keluarga','Usia','Keterangan'], 'required'],
            [['Keterangan'], 'string'],
              [['Email_Peserta'], 'email'],
            [['Nama_Peserta'], 'string', 'max' => 250],
            [['Email_Peserta', 'No_HP', 'NIK', 'Kategori_City_Bike', 'Ukuran_Jersey', 'Nama_Anggota_Keluarga','Usia'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Kode_Citybike' => 'Kode  Citybike',
            'Nama_Peserta' => 'Nama  Peserta',
            'Email_Peserta' => 'Email  Peserta',
            'No_HP' => 'No  Hp',
            'NIK' => 'NIK',
            'Kategori_City_Bike' => 'Jarak Tempuh',
            'Ukuran_Jersey' => 'Ukuran  Jersey',
            'Nama_Anggota_Keluarga' => 'Departemen',
            'Keterangan' => 'Jenis Sepeda Yang Digunakan',
            'Jenis_Kelamin'=>'Jenis Kelamin',
            'Usia'=>'Usia'
        ];
    }
    
      /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransactionDetails()
    {
        return $this->hasMany(Anggotakeluarga::className(), ['Kode_Citybike' => 'Kode_Citybike']);
    }
}

controllers/CitybikeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Citybike;
use app\models\CitybikeSearch;
use app\models\Anggotakeluarga;
use app\models\AnggotakeluargaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Model;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;

/**
 * CitybikeController implements the CRUD actions for Citybike model.
 */
class CitybikeController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Citybike models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new CitybikeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Citybike model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        //detail Sales
        $detailQuery = Anggotakeluarga::find()
                ->where(['Kode_Citybike' => $id])
        ;
        $detailDataProvider = new ActiveDataProvider([
            'query' => $detailQuery,
        ]);

        return $this->render('view', [
                    'model' => $this->findModel($id),
                    'detailDataProvider' => $detailDataProvider
        ]);
    }

    /**
     * Creates a new Citybike model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Citybike();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Kode_Citybike]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionRegister() {
        $model = new Citybike();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->sendmail($model->Kode_Citybike);
            Yii::$app->session->setFlash('success', Yii::$app->params['pendaftaransukses']);
            return $this->redirect(['/site/index']);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionRegisterwithfamily() {
        $model = new Citybike();
        $details = [ new Anggotakeluarga];

        // proses isi post variable 
        if ($model->load(Yii::$app->request->post())) {
            $details = Model::createMultiple(Anggotakeluarga::classname());
            Model::loadMultiple($details, Yii::$app->request->post());

            // assign default transaction_id
            foreach ($details as $detail) {
                $detail->Kode_Citybike = 0;
            }

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                                ActiveForm::validateMultiple($details), ActiveForm::validate($model)
                );
            }

            // validate all models
            $valid1 = $model->validate();
            $valid2 = Model::validateMultiple($details);
            $valid = $valid1 && $valid2;

            // jika valid, mulai proses penyimpanan
            if ($valid) {
                // mulai database transaction
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    // simpan master record                   
                    if ($flag = $model->save(false)) {
                        // simpan details record
                        foreach ($details as $detail) {
                            $detail->Kode_Citybike = $model->Kode_Citybike;
                            if (!($flag = $detail->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        // sukses, commit database transaction
                        // kemudian tampilkan hasilnya
                        $transaction->commit();
                        $this->sendmail($model->Kode_Citybike);
                        Yii::$app->session->setFlash('success', Yii::$app->params['pendaftaransukses']);
                        return $this->redirect(['/site/index']);
                    } else {
                        return $this->render('createwithfamily', [
                                    'model' => $model,
                                    'details' => $details,
                        ]);
                    }
                } catch (Exception $e) {
                    // penyimpanan galga, rollback database transaction
                    $transaction->rollBack();
                    throw $e;
                }
            } else {
                return $this->render('create', [
                            'model' => $model,
                            'details' => $details,
                            'error' => 'valid1: ' . print_r($valid1, true) . ' - valid2: ' . print_r($valid2, true),
                ]);
            }
        } else {
            // inisialisai id 
            // diperlukan untuk form master-detail
            $model->Kode_Citybike = 0;
            // render view
            return $this->render('createwithfamily', [
                        'model' => $model,
                        'details' => $details,
            ]);
        }
    }

    public function actionRegisterawal() {
        return $this->render('registerawal');
    }

    /**
     * Updates an existing Citybike model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Kode_Citybike]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Citybike model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    /* public function actionDelete($id)
      {
      $this->findModel($id)->delete();

      return $this->redirect(['index']);
      } */

    public function actionDelete($id) {
        $model = $this->findModel($id);
        $details = $model->transactionDetails;
        // mulai database transaction
        $transaction = \Yii::$app->db->beginTransaction();
        try {
            // pertama, delete semua detail records
            foreach ($details as $detail) {
                $detail->delete();
            }
            // kemudian, delete master record
            $model->delete();
            // sukses, commit transaction
            $transaction->commit();
        } catch (Exception $e) {
            // gagal, rollback database transaction
            $transaction->rollBack();
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the Citybike model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Citybike the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Citybike::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    //Export Excel
    public function actionExportExcel() {
        $searchModel = new CitybikeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = 0;

        $style = array(
            'alignment' => array(
                'horizontal' => \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
            )
        );

        $styleArrayRightThin = array(
            'borders' => array(
                'right' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_THIN
                )
            )
        );

        $styleArrayLeftThin = array(
            'borders' => array(
                'left' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_THIN
                )
            )
        );

        $styleArrayLeftMedium = array(
            'borders' => array(
                'left' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

        $styleArrayRightMedium = array(
            'borders' => array(
                'right' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

        $styleArrayBottomMedium = array(
            'borders' => array(
                'bottom' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

        $styleArrayTopMedium = array(
            'borders' => array(
                'top' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

views/citybike/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Citybike */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="citybike-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'Nama_Peserta')->textInput(['maxlength' => true]) ?>
    
      <?= $form->field($model, 'Jenis_Kelamin')->dropDownList(Yii::$app->params['jeniskelamin']);?>
        
    <?= $form->field($model, 'Usia')->textInput(['maxlength' => true]) ?>

     <?= $form->field($model, 'NIK')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'Nama_Anggota_Keluarga')->textInput(['maxlength' => true]) ?>
    
    
    <?= $form->field($model, 'Email_Peserta')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'No_HP')->textInput(['maxlength' => true]) ?>   

      <?=$form->field($model, 'Kategori_City_Bike')->dropDownList(Yii::$app->params['kategoricitybike']);?>

     <?=$form->field($model, 'Ukuran_Jersey')->dropDownList(Yii::$app->params['ukuranjersey']);?>

    
    
     <?=$form->field($model, 'Keterangan')->dropDownList(Yii::$app->params['jenissepeda']);?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Register' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/citybike/_formwithfamily.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


use wbraganca\dynamicform\DynamicFormWidget;


/* @var $this yii\web\View */
/* @var $model app\models\Charitywalk */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transactions-form">

    <?php $form = ActiveForm::begin(['id' => 'transactions-form']); ?>

 <?= $form->field($model, 'Nama_Peserta')->textInput(['maxlength' => true]) ?>
    
      <?= $form->field($model, 'Jenis_Kelamin')->dropDownList(Yii::$app->params['jeniskelamin']);?>
        
    <?= $form->field($model, 'Usia')->textInput(['maxlength' => true]) ?>

     <?= $form->field($model, 'NIK')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'Nama_Anggota_Keluarga')->textInput(['maxlength' => true]) ?>
    
    
    <?= $form->field($model, 'Email_Peserta')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'No_HP')->textInput(['maxlength' => true]) ?>   

      <?=$form->field($model, 'Kategori_City_Bike')->dropDownList(Yii::$app->params['kategoricitybike']);?>

     <?=$form->field($model, 'Ukuran_Jersey')->dropDownList(Yii::$app->params['ukuranjersey']);?>

    
    
     <?=$form->field($model, 'Keterangan')->dropDownList(Yii::$app->params['jenissepeda']);?>

    <div class="panel panel-default">
        <div class="panel-heading"><h4><i class="glyphicon glyphicon-th-list"></i> Anggota keluarga yang ikut</h4></div>
        <div class="panel-body">
             <?php DynamicFormWidget::begin([
                'widgetContainer' => 'dynamicform_wrapper',  // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                'widgetBody' => '.container-items',          // required: css class selector
                'widgetItem' => '.item',                     // required: css class
                'limit' => 20,                                // the maximum times, an element can be cloned (default 999)
                'min' => 1,                                  // 0 or 1 (default 1)
                'insertButton' => '.add-item',               // css class
                'deleteButton' => '.remove-item',            // css class
                'model' => $details[0],
                'formId' => 'transactions-form',
                'formFields' => [
                    'trans_id',
                    'item_id',
                    'quantity',
                    'remarks',
                ],
            ]); ?>

            <div class="container-items"><!-- widgetContainer -->
            <?php foreach ($details as $i => $detail): ?>
                <div class="item row">
                    <?php
                        // necessary for update action.
                        if (! $detail->isNewRecord) {
                            echo Html::activeHiddenInput($detail, "[{$i}]Kode_Citybike");
                        }
                    ?>
                    <div class="col-sm-6 col-md-2">
                         <?= $form->field($detail, "[{$i}]Nama")->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-sm-6 col-md-1">
                        <?= $form->field($detail, "[{$i}]Usia")->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-sm-6 col-md-2">
                    	  <?=$form->field($detail, "[{$i}]Jenis_Kelamin")->dropDownList(Yii::$app->params['jeniskelamin']);?>
     
                    </div>
                    
                     <div class="col-sm-6 col-md-2">
                    	 <?=$form->field($detail, "[{$i}]Ukuran_Jersey")->dropDownList(Yii::$app->params['ukuranjerseycitybike']);?>
                    </div>
                    
                    <div class="col-sm-6 col-md-2">
                    	 <?=$form->field($detail, "[{$i}]field1")->dropDownList(Yii::$app->params['kategoricitybike']);?>
                    </div>
                    
                       <div class="col-sm-6 col-md-2">
                    	<?= $form->field($detail, "[{$i}]Jenis_Sepeda")->dropDownList(Yii::$app->params['jenissepeda']);?>
                    </div>
                    
                    <div class="col-sm-2 col-md-1 item-action">
                    	<div class="pull-right">
	                        <button type="button" class="add-item btn btn-success btn-xs">
	                        	<i class="glyphicon glyphicon-plus"></i></button> 
	                        <button type="button" class="remove-item btn btn-danger btn-xs">
	                        	<i class="glyphicon glyphicon-minus"></i></button>
                    	</div>
                    </div>
                </div><!-- .row -->

            <?php endforeach; ?>
            </div>

            <?php DynamicFormWidget::end(); ?>
        </div>
    </div>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Register') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/citybike/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CitybikeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="citybike-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'Kode_Citybike') ?>

    <?= $form->field($model, 'Nama_Peserta') ?>

    <?= $form->field($model, 'Email_Peserta') ?>

    <?= $form->field($model, 'No_HP') ?>

    <?= $form->field($model, 'NIK') ?>

    <?php // echo $form->field($model, 'Kategori_City_Bike') ?>

    <?php // echo $form->field($model, 'Ukuran_Jersey') ?>

    <?php // echo $form->field($model, 'Nama_Anggota_Keluarga') ?>

    <?php // echo $form->field($model, 'Keterangan') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/citybike/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Citybike */

$this->title = 'Register Gowes Bareng';
//$this->params['breadcrumbs'][] = ['label' => 'Citybikes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citybike-create">

  

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/citybike/createwithfamily.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Citybike */

$this->title = 'Register Gowes Bareng';
//$this->params['breadcrumbs'][] = ['label' => 'Citybikes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citybike-create">

 

    <?= $this->render('_formwithfamily', [
        'model' => $model,
        'details' => $details,
    ]) ?>

</div>

views/citybike/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CitybikeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Gowes Bareng';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citybike-index">

    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Register City Bike', ['registerawal'], ['class' => 'btn btn-success']) ?>
        
          <?= Html::a('Anggota Keluarga Yg Ikut', ['/anggotakeluarga/index'], ['class' => 'btn btn-primary']) ?>

        <?php
        $urlexcel = array_filter(Yii::$app->getRequest()->get());
        $urlexcel[0] = 'export-excel';
        unset($urlexcel['page']);
        ?>

        <?= Html::a('Export Excel ', $urlexcel, ['class' => 'btn btn-info', 'target' => '_blank']); ?>
    </p>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'summary' => Yii::$app->params['summary'],
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'Kode_Citybike',
            'Nama_Peserta',
            'Jenis_Kelamin',
            'Email_Peserta:email',
            'No_HP',
            'NIK',
            'Kategori_City_Bike',
            'Ukuran_Jersey',
            'Nama_Anggota_Keluarga',
            'Keterangan',
            [
                'class' => 'yii\grid\ActionColumn',
                'template'=>'{view}{delete}'
            ],
        ],
    ]);
    ?>
</div>

views/citybike/registerawal.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CitybikeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Apakah ada anggota keluarga yang ikut serta pada gowes bareng?';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citybike-index">

 
    <p>
        <?= Html::a('Ada', ['/citybike/registerwithfamily'], ['class' => 'btn btn-success']) ?>
        
       <?= Html::a('Tidak Ada', ['/citybike/register'], ['class' => 'btn btn-primary']) ?>
    </p>
  
</div>

views/citybike/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Citybike */

$this->title = 'Update Citybike: ' . $model->Kode_Citybike;
//$this->params['breadcrumbs'][] = ['label' => 'Citybikes', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->Kode_Citybike, 'url' => ['view', 'id' => $model->Kode_Citybike]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citybike-update">

  

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/citybike/updatewithfamily.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Citybike */

$this->title = 'Update Citybike: ' . $model->Kode_Citybike;
//$this->params['breadcrumbs'][] = ['label' => 'Citybikes', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->Kode_Citybike, 'url' => ['view', 'id' => $model->Kode_Citybike]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citybike-update">



    <?= $this->render('_formwithfamily', [
        'model' => $model,
        'details' => $details,
    ]) ?>

</div>

views/citybike/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Citybike */

$this->title = "Peserta : ".$model->Nama_Peserta;
//$this->params['breadcrumbs'][] = ['label' => 'Citybikes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citybike-view">



    <p>
        <?= Html::a('Update', ['update', 'id' => $model->Kode_Citybike], ['class' => 'btn btn-primary']) ?>
         <?= Html::a('Update With Family', ['updatewithfamily', 'id' => $model->Kode_Citybike], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->Kode_Citybike], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
         <?= Html::a('Export Form ', ['export-form','id'=>$model->Kode_Citybike], ['class' => 'btn btn-info', 'target' => '_blank']); ?>
        <?= Html::a('List', ['index'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'Kode_Citybike',
            'Nama_Peserta',
            'Jenis_Kelamin',
            'Email_Peserta:email',
            'No_HP',
            'NIK',
            'Kategori_City_Bike',
            'Ukuran_Jersey',
            'Nama_Anggota_Keluarga',
            'Keterangan',
        ],
    ]) ?>
    
      <h3>Daftar anggota Keluarga yg ikut</h3>
    <?=
    GridView::widget([
        'dataProvider' => $detailDataProvider,
        //  'filterModel' => $searchModel,
        'summary' => Yii::$app->params['summary'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
           // 'Kode_Peserta',
            //'Kode_Charitywalk',
            'Nama',
            'Usia',
            'Jenis_Kelamin',
             'Ukuran_Jersey',
            'field1',
          
             'Jenis_Sepeda',
            //['class' => 'yii\grid\ActionColumn'],
        ],
    ]);
    ?>

</div>