models/Anggotakeluarga.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "anggotakeluarga".
 *
 * @property integer $Kode_Peserta
 * @property integer $Kode_Citybike
 * @property string $Nama
 * @property string $Jenis_Kelamin
 * @property string $Ukuran_Jersey
 * @property string $Usia
 * @property string $Jenis_Sepeda
 * @property string $field1
 * @property string $filed2
 * @property string $field3
 */
class Anggotakeluarga extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'anggotakeluarga';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Kode_Citybike', 'Nama', 'Jenis_Kelamin', 'Ukuran_Jersey', 'Usia', 'Jenis_Sepeda'], 'required'],
            [['Kode_Citybike'], 'integer'],
            [['Nama', 'Ukuran_Jersey', 'Usia', 'Jenis_Sepeda', 'field1', 'filed2', 'field3'], 'string', 'max' => 200],
            [['Jenis_Kelamin'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Kode_Peserta' => 'Kode  Peserta',
            'Kode_Citybike' => 'Peserta',
            'Nama' => 'Nama',
            'Jenis_Kelamin' => 'Jenis  Kelamin',
            'Ukuran_Jersey' => 'Ukuran  Jersey',
            'Usia' => 'Usia',
            'Jenis_Sepeda' => 'Jenis  Sepeda',
            'field1' => 'Jarak Tempuh',
            'filed2' => 'Filed2',
            'field3' => 'Field3',
        ];
    }
    
    public function getCitybike()
    {
        return $this->hasOne(Citybike::className(), ['Kode_Citybike' => 'Kode_Citybike']);
    }
}

controllers/CitybikeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Citybike;
use app\models\CitybikeSearch;
use app\models\Anggotakeluarga;
use app\models\AnggotakeluargaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Model;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;

/**
 * CitybikeController implements the CRUD actions for Citybike model.
 */
class CitybikeController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Citybike models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new CitybikeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Citybike model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        //detail Sales
        $detailQuery = Anggotakeluarga::find()
                ->where(['Kode_Citybike' => $id])
        ;
        $detailDataProvider = new ActiveDataProvider([
            'query' => $detailQuery,
        ]);

        return $this->render('view', [
                    'model' => $this->findModel($id),
                    'detailDataProvider' => $detailDataProvider
        ]);
    }

    /**
     * Creates a new Citybike model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Citybike();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Kode_Citybike]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionRegister() {
        $model = new Citybike();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->sendmail($model->Kode_Citybike);
            Yii::$app->session->setFlash('success', Yii::$app->params['pendaftaransukses']);
            return $this->redirect(['/site/index']);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionRegisterwithfamily() {
        $model = new Citybike();
        $details = [ new Anggotakeluarga];

        // proses isi post variable 
        if ($model->load(Yii::$app->request->post())) {
            $details = Model::createMultiple(Anggotakeluarga::classname());
            Model::loadMultiple($details, Yii::$app->request->post());

            // assign default transaction_id
            foreach ($details as $detail) {
                $detail->Kode_Citybike = 0;
            }

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                                ActiveForm::validateMultiple($details), ActiveForm::validate($model)
                );
            }

            // validate all models
            $valid1 = $model->validate();
            $valid2 = Model::validateMultiple($details);
            $valid = $valid1 && $valid2;

            // jika valid, mulai proses penyimpanan
            if ($valid) {
                // mulai database transaction
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    // simpan master record                   
                    if ($flag = $model->save(false)) {
                        // simpan details record
                        foreach ($details as $detail) {
                            $detail->Kode_Citybike = $model->Kode_Citybike;
                            if (!($flag = $detail->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        // sukses, commit database transaction
                        // kemudian tampilkan hasilnya
                        $transaction->commit();
                        $this->sendmail($model->Kode_Citybike);
                        Yii::$app->session->setFlash('success', Yii::$app->params['pendaftaransukses']);
                        return $this->redirect(['/site/index']);
                    } else {
                        return $this->render('createwithfamily', [
                                    'model' => $model,
                                    'details' => $details,
                        ]);
                    }
                } catch (Exception $e) {
                    // penyimpanan galga, rollback database transaction
                    $transaction->rollBack();
                    throw $e;
                }
            } else {
                return $this->render('create', [
                            'model' => $model,
                            'details' => $details,
                            'error' => 'valid1: ' . print_r($valid1, true) . ' - valid2: ' . print_r($valid2, true),
                ]);
            }
        } else {
            // inisialisai id 
            // diperlukan untuk form master-detail
            $model->Kode_Citybike = 0;
            // render view
            return $this->render('createwithfamily', [
                        'model' => $model,
                        'details' => $details,
            ]);
        }
    }

    public function actionRegisterawal() {
        return $this->render('registerawal');
    }

    /**
     * Updates an existing Citybike model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Kode_Citybike]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Citybike model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    /* public function actionDelete($id)
      {
      $this->findModel($id)->delete();

      return $this->redirect(['index']);
      } */

    public function actionDelete($id) {
        $model = $this->findModel($id);
        $details = $model->transactionDetails;
        // mulai database transaction
        $transaction = \Yii::$app->db->beginTransaction();
        try {
            // pertama, delete semua detail records
            foreach ($details as $detail) {
                $detail->delete();
            }
            // kemudian, delete master record
            $model->delete();
            // sukses, commit transaction
            $transaction->commit();
        } catch (Exception $e) {
            // gagal, rollback database transaction
            $transaction->rollBack();
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the Citybike model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Citybike the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Citybike::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    //Export Excel
    public function actionExportExcel() {
        $searchModel = new CitybikeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = 0;

        $style = array(
            'alignment' => array(
                'horizontal' => \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
            )
        );

        $styleArrayRightThin = array(
            'borders' => array(
                'right' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_THIN
                )
            )
        );

        $styleArrayLeftThin = array(
            'borders' => array(
                'left' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_THIN
                )
            )
        );

        $styleArrayLeftMedium = array(
            'borders' => array(
                'left' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

        $styleArrayRightMedium = array(
            'borders' => array(
                'right' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

        $styleArrayBottomMedium = array(
            'borders' => array(
                'bottom' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

        $styleArrayTopMedium = array(
            'borders' => array(
                'top' => array(
                    'style' => \PHPExcel_Style_Border::BORDER_MEDIUM
                )
            )
        );

views/anggotakeluarga/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Anggotakeluarga */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="anggotakeluarga-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'Kode_Citybike')->textInput() ?>

    <?= $form->field($model, 'Nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Jenis_Kelamin')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Ukuran_Jersey')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Usia')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Jenis_Sepeda')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'field1')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'filed2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'field3')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/anggotakeluarga/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AnggotakeluargaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="anggotakeluarga-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'Kode_Peserta') ?>

    <?= $form->field($model, 'Kode_Citybike') ?>

    <?= $form->field($model, 'Nama') ?>

    <?= $form->field($model, 'Jenis_Kelamin') ?>

    <?= $form->field($model, 'Ukuran_Jersey') ?>

    <?php // echo $form->field($model, 'Usia') ?>

    <?php // echo $form->field($model, 'Jenis_Sepeda') ?>

    <?php // echo $form->field($model, 'field1') ?>

    <?php // echo $form->field($model, 'filed2') ?>

    <?php // echo $form->field($model, 'field3') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/anggotakeluarga/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Anggotakeluarga */

$this->title = 'Create Anggotakeluarga';
$this->params['breadcrumbs'][] = ['label' => 'Anggotakeluargas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anggotakeluarga-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/anggotakeluarga/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AnggotakeluargaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Anggota Keluarga Yang Ikut';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anggotakeluarga-index">

    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
             <?= Html::a('City Bike', ['/citybike/index'], ['class' => 'btn btn-success']) ?>

        <?php
        $urlexcel = array_filter(Yii::$app->getRequest()->get());
        $urlexcel[0] = 'export-excel';
        unset($urlexcel['page']);
        ?>

        <?= Html::a('Export Excel ', $urlexcel, ['class' => 'btn btn-info', 'target' => '_blank']); ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summary'=>  Yii::$app->params['summary'],
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           // 'Kode_Peserta',
            //'Kode_Citybike',
              [
                'attribute' => 'Kode_Citybike',
                'value' => 'citybike.Nama_Peserta',
                'filter' => Html::activeDropDownList($searchModel, 'Kode_Citybike', ArrayHelper::map(\app\models\Citybike::find()->orderBy(['Nama_Peserta' => SORT_ASC])->asArray()->all(), 'Kode_Citybike', 'Nama_Peserta'), ['class' => 'form-control', 'prompt' => 'Semua Peserta']),
            ],
            'Nama',
            'Jenis_Kelamin',
            'Ukuran_Jersey',
             'Usia',
             'Jenis_Sepeda',
             'field1',
            // 'filed2',
            // 'field3',

           // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/anggotakeluarga/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Anggotakeluarga */

$this->title = 'Update Anggota Keluarga: ' . $model->Kode_Peserta;
//$this->params['breadcrumbs'][] = ['label' => 'Anggotakeluargas', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->Kode_Peserta, 'url' => ['view', 'id' => $model->Kode_Peserta]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anggotakeluarga-update">

  

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/anggotakeluarga/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Anggotakeluarga */

$this->title = $model->Kode_Peserta;
//$this->params['breadcrumbs'][] = ['label' => 'Anggotakeluargas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anggotakeluarga-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->Kode_Peserta], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->Kode_Peserta], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'Kode_Peserta',
            'Kode_Citybike',
            'Nama',
            'Jenis_Kelamin',
            'Ukuran_Jersey',
            'Usia',
            'Jenis_Sepeda',
            'field1',
            'filed2',
            'field3',
        ],
    ]) ?>

</div>